### PR TITLE
Add support for more package managers

### PR DESCRIPTION
**Pull request by AlbydST**
Most of the commands were taken from [hyfetch](https://github.com/hykilpikonna/hyfetch). I just adapted them to work with your package count function.

### CODE REVIEW

**Comment by Un1q32** [comment]
Radula support was removed by the creator of the package manager, it's my understanding that the distro it comes from is experimental enough that basically everyone using it has the latest version.

**Comment by Un1q32** [comment]
IIRC the pm package manager, setup like this, will incorrectly print 1 package if the user running it doesn't have permissions to use pm (for example when running in termux).  Hyfetch fixed this but I forgot how.

**Comment by AlbydST** [comment]
> Radula support was removed by the creator of the package manager, it's my understanding that the distro it comes from is experimental enough that basically everyone using it has the latest version.

I guess if you want I can remove it. I just always try to support as many systems as possible.

>  Hyfetch fixed this but I forgot how.

They made it so it counts packages only if the command succeeds. See commit [176f08ad0b6ef33b82a6d24e33baefeeedfaccda](https://github.com/hykilpikonna/hyfetch/commit/176f08ad0b6ef33b82a6d24e33baefeeedfaccda). Maybe this could be implemented here aswell?

**Comment by Un1q32** [comment]
Also there are a lot of bashisms in your PR, you can run shellcheck on your script to see what needs fixing.

**Comment by Un1q32** [comment]
Rebase on the latest commit and remove radula please, I added pm support myself and that causes a merge conflict.

Also please try and keep your lines from getting too long.

**Pull request merged**
