### PR TITLE
cpus for NetBSD

### PR DESCRIPTION
**Pull request by polluks**

### CODE REVIEW

**Comment by Un1q32** [comment]
This breaks macOS, as sysctl is in /usr/sbin/sysctl there.  NetBSD should get it's own part in the case statement.

**Comment by Un1q32** [comment]
Screenshot 2024-09-18 at 4 32 56 PM

github is a very stable and not broken website

**Comment by polluks** [comment]
oops

**Comment by Un1q32** [comment]
why close this?

**Pull request merged**
