### PR TITLE
Adding a man page

### PR DESCRIPTION
**Pull request by danielhejduk**
This PR adds a man page for pfetch.  #50 

It is not completed but I am working on it. I am making this PR to track my work.

### CODE REVIEW

**Comment by danielhejduk** [comment]
image

**Comment by Un1q32** [comment]
Converted to draft, click on ready for review when you think it's ready.

**Comment by danielhejduk** [comment]
I think it is done

**Comment by Un1q32** [comment]
Would like the other info in readme like the default options and examples, but I'm not sure of the best way to do that is in a man page.  I'll figure it out later

**Pull request merged**
