### PR TITLE
Add OpenIndiana's logo. 

### PR DESCRIPTION
**Pull request by xplshn**
OpenIndiana is OpenSolaris' successor, so, no special logic shall be added for it to work

Also, I am using C7 so show white, is there no way to display gray?

### CODE REVIEW

**Comment by xplshn** [comment]
Note: Logo was generated using the small version of OpenIndiana's logo in combination with this command: `chafa --scale=0.3 --colors=8 --fg-only --invert --format symbols --symbols braille /tmp/openindiana_logo.png`

**Comment by Un1q32** [comment]
Currently doesn't work

2024-03-14-183456_hyprshot

**Comment by xplshn** [comment]
Set distro? It works fine in my OpenIndiana install

**Comment by xplshn** [comment]
Maybe it has to do with the fact I used cat to see the contents of the file, copied and pasted the modification in Github's editor, rather than doing a proper fork. I will modify the file right now

**Comment by xplshn** [comment]
Could you please check again now?

**Comment by Un1q32** [comment]
Better, but running in dash instead of bash does this

image

**Comment by xplshn** [comment]
Seems like a problem with BASH, I just installed BASH to test and the issue wasn't present either

**Comment by xplshn** [comment]
Have you checked if something changes with POSIXLY_CORRECT=1?

**Comment by Un1q32** [comment]
image

**Comment by xplshn** [comment]
I am not sure what this line does, I copied Solaris's ASCII logo as a template first. `read_ascii 3 <<-EOF`

**Comment by xplshn** [comment]
It had to do with my editor replacing tabs with spaces... Since you cannot use spaces with <<-

I will commit a fix

**Comment by Un1q32** [comment]
image

**Comment by xplshn** [comment]
Sorry to bother so much, I think I fixed it. I ran with DASH to test and no issues, I also tested with busybox's ASH, and KSH which is my shell.

**Comment by Un1q32** [comment]
Did you mean to commit something?  I'm not seeing it.

**Comment by Un1q32** [comment]
> image

This is taken with the latest commit

**Comment by xplshn** [comment]
If the issue is not fixed I really don't know what would be the cause. Sorry to have caused problems, do not add this if its too much work. I wasn't able to open your screenshot but I guess the problem remains. I don't know why it is hosted at private-user-images.githubusercontent.com

https://private-user-images.githubusercontent.com/57970114/313017986-ad8a4ba6-3964-41a6-80d7-46245540567d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1Mzg3NTUsIm5iZiI6MTcxMDUzODQ1NSwicGF0aCI6Ii81Nzk3MDExNC8zMTMwMTc5ODYtYWQ4YTRiYTYtMzk2NC00MWE2LTgwZDctNDYyNDU1NDA1NjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDIxMzQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiMzRiOGZhZGJiOWJlNjhkODBiNGQxMTVhODVlMjM3NDkwYjRmNDY5Yjc1MWNhZTAzZGMxYzk1MDRiNjMzNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rmkCjUIx4QkojExWUqUCXHzG8TItFq6H0aQrnxY-1Ik

**Comment by Un1q32** [comment]
I think the issue is due to the special characters used in the logo, some shells behave weird with them, if you can design a logo with just normal ASCII characters that would be better, plus I think some terminals (like the linux tty) don't support braille characters anyway

**Comment by xplshn** [comment]
Sure. I will try again then, sorry to bother

**Comment by xplshn** [comment]
Came up with this one but I couldn't get it to display nicely.
```
                              
                   XXX        
                              
        .xxxxx.    .X         
      .xx     xx.  .X         
     .x.       .x. .X       x.
     +x         xx .X        x
     .x.        x. .X      .x 
      .xx     ;x:  .X    ;x   
   ..   .xxxxx.    .X .x.     
 .                .xx.        
x            .xxx.            
+x+...;xxxxx.
```


```
]@ PF_ASCII=openindiana ksh .pfetch
                                   XXanto@pink
                                     os     Alpine Linux edge
                        .xxxxx.    .Xhost   VJF155A2011B
                      .xx     xx.  .Xkernel 6.7.9-0-edge
                     .x.       .x. .Xuptime 12h 50m
                     +x         xx .Xpkgs   253
                     .x.        x. .Xmemory.2560M / 3818M
                      .xx     ;x:  .X    ;x
                   ..   .xxxxx.    .X .x.
                 .                .xx.
                x            .xxx.
                +x+...;xxxxx.

]@
```

**Comment by xplshn** [comment]
At least the old one works in OpenIndiana

**Comment by xplshn** [comment]
Here's the one that doesn't work:
```
        ([Oo]pen[Ii]ndiana*)
            read_ascii 3 <<-EOF
                ${c7}                   XXX
                ${c7}
                ${c7}        ${c4}.xxxxx.${c7}    .X
                ${c7}      ${c4}.xx     xx.${c7}  .X
                ${c7}     ${c4}.x.       .x.${c7} .X       x.
                ${c7}     ${c4}+x         xx${c7} .X        x
                ${c7}     ${c4}.x.        x.${c7} .X      .x
                ${c7}      ${c4}.xx     ;x:${c7}  .X    ;x
                ${c7}   ..   ${c4}.xxxxx.${c7}    .X .x.
                ${c7} .                .xx.
                ${c7}x            .xxx.
                ${c7}+x+...;xxxxx.
                        EOF
        ;;
```

**Comment by Un1q32** [comment]
Probably too big

**Pull request closed without merging**
